version: '3.8'

services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
      SA_PASSWORD: cveZ8MzjH5AeYPVe
    volumes:
      - ./mssqlsystem:/var/opt/mssql
      - ./mssqluser:/var/opt/sqlserver
